### ISSUE TITLE
Lima - Menu Target Links

### ISSUE THREAD

**Issue by Ink-WeiZhang** [justweison/starter-route66#21]
- Add target link /able for Alpha
- Add target link /bravo for Bravo
- Add target link /charlie/brown for Charlie
- Add target link /delta/force for Delta
- Add target link /echo/must/wehave for Echo
- Add target link /foxtrot for Foxtrot
- Add target link /i/need/a/hobby for Golf
- Add target link /bananas/rule for Hotel
- Add target link /india for India
- Add target link /juliet for Juliet
- Add target link /show/2 for Kilo

**Comment by Justin-Leung** [comment]
@Ink-WeiZhang taking this issue.

None of the menu links work. Fixing because the target links weren't added during development.
